### PR TITLE
Add support for multiple configs

### PR DESCRIPTION
**Pull request by amatosov-rbx**
This change allows having array of configurations or a single configuration in xcodebuild-tools.json
UI picker is provided to switch active configuration (workspace/scheme)

### CODE REVIEW

**Comment by sterin** [comment]
Hi Anaton,

Thanks for the PR. Would you mind making some changes and resubmit?

1. I've made a bit of a mess in the history by rebasing your previous PR. Could you graft your changes into the current master? Sorry for that.

2. I have no idea how many users are using the extension, but I would rather not break backward compatibility. Could you check for the existing settings and add them as an additional configuration if possible.

3. I think there's no need for a "configuration" field and "configurationArray". I think just a single array "configurations" might work.

Thanks,
Baruch

**Comment by amatosov-rbx** [comment]
Hi @sterin,

1. I'll do the clean rebase
2. These changes are backward compatible
3. This is needed for backward compatibility

**Comment by sterin** [comment]
Hi @amatosov-rbx,

Great. So the "oneOf" refers to the top-level element giving the choice between a top-level array and an object, right?

**Comment by amatosov-rbx** [comment]
Correct. 
oneOf is well explained here https://json-schema.org/understanding-json-schema/reference/combining.html

**Comment by amatosov-rbx** [comment]
I have found couple issues with this PR, I'll reopen it once I have the proper fix

**Comment by amatosov-rbx** [comment]
Re-open didn't work because of rebase. Opened new PR https://github.com/sterin/vscode-xcodebuild-tools/pull/6

**Pull request closed without merging**
